/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_espace_admin (void);
GtkWidget* create_espace_ajout_Utilisateur (void);
GtkWidget* create_espace_modif_Utilisateur (void);
GtkWidget* create_espace_supprimer_Utilisateur (void);
GtkWidget* create_espace_Statistique_Utilisateur (void);
GtkWidget* create_espace_Afficher_Utilisateur (void);
GtkWidget* create_Acceuil_App (void);
GtkWidget* create_espace_infirmier (void);
GtkWidget* create_espace_ajouter_donneur (void);
GtkWidget* create_Espace_modifier_donneur (void);
GtkWidget* create_Espace_Supp_Donneur (void);
GtkWidget* create_espace_Afficher_donneur (void);
GtkWidget* create_Espace_stat_donneur (void);
GtkWidget* create_espace_medecin (void);
GtkWidget* create_espace_Ajouter_don_ghada (void);
GtkWidget* create_espace_modif_dons (void);
GtkWidget* create_Espace_supp_Dons (void);
GtkWidget* create_espace_ghada_affiche (void);
GtkWidget* create_espace_stat_dons (void);
GtkWidget* create_Espace_ets_oussema (void);
GtkWidget* create_NL_Ajouter_ETS (void);
GtkWidget* create_NL_Modifier_ETS (void);
GtkWidget* create_NL_Afficher_ETS (void);
GtkWidget* create_NL_Supprimer_ETS (void);
